const BLOG_SCHEMA_CONSTS = Object.freeze({
  TITLE_MAX_LENGTH: 100,
  TITLE_MIN_LENGTH: 4,
  CONTENT_MAX_LENGTH: 6000,
  CONTENT_MIN_LENGTH: 150,
  THUMBNAIL_MAX_LENGTH: 500,
  BLOG_CATEGORIES: [
    "Application Development",
    "AI/ML",
    "Data Science & Analytics",
    "Cyber Security",
    "IOT",
    "Games Development",
    "Other Technology",
    "Commerce",
    "Finance",
    "Taxes",
    "Economy",
    "Travel",
    "Food",
    "Fashion",
    "Health",
    "Lifestyle",
    "Sciences",
    "Sports",
    "Entertainment",
    "Other",
  ].map(c => c.toLowerCase()),
  COMMENT_MAX_LENGTH: 150,
  COMMENT_MIN_LENGTH: 1,
});

module.exports = BLOG_SCHEMA_CONSTS;
